apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop.fullname" . }}-config
  labels:
    {{- include "shop.labels" . | nindent 4 }}
data:
  USER: {{ .Values.env.user | quote }}
  MYSQL_HOST: {{ .Values.env.mysqlHost | quote }}
  API_BASE_URL: {{ .Values.env.apiBaseUrl | quote }}
  TITLE_IMAGE: {{ .Values.titleImage | default "default.png" | quote }}