name: Build and Push OCI
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        env:
          ACTOR_LOWER: ${{ github.actor }}
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${ACTOR_LOWER,,} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push API
        env:
          REPO_LOWER: ${{ github.repository }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${REPO_LOWER,,}/api:latest \
            --push ./api

      - name: Build & Push UI
        env:
          REPO_LOWER: ${{ github.repository }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${REPO_LOWER,,}/ui:latest \
            --push ./ui

      - name: Package and Push Helm Chart
        env:
          OWNER_LOWER: ${{ github.repository_owner }}
        run: |
          helm package ./helm-chart
          # Note: We push to the 'charts' namespace in lowercase
          helm push *.tgz oci://ghcr.io/${OWNER_LOWER,,}
